# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseFramework

  pod 'AFNetworking', '~> 3.0'

  pod 'Masonry', '~> 1.0.2'

  pod 'SDWebImage', '~>3.7'

  target 'BaseFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseFrameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
